version: '3'
services:
  app:
    build: docker/php
    container_name: jetig_app
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    image: nginx:1.21
    container_name: jetig_nginx
    ports:
      - 2607:80
      - 8090:8090
    volumes:
      - ./:/var/www
      - ./docker/nginx/jetig_net.local.conf:/etc/nginx/conf.d/jetig_net.local.conf

    depends_on:
      - app
  db:

    image: mysql:8.0.23
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/mysql/files:/var/lib/mysql
    container_name: jetig_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: jetig_db
      MYSQL_USER: jetig_user
      MYSQL_PASSWORD: 123456
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 26071:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=jetig.local